<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Me livrando da Maldição</title>
</head>
<body>
    <h1>
        <?php
        echo "Olám, Mundo!\u{IF30E}"
        ?>
<p> Vamos tentar nos livar da Maldição</p>
</body>
</html>